name: REGON - RELEASE NEW VERSION TO NUGET.ORG

on:
  release:
    types: [released]

jobs:
  publishing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: âš™ï¸ Install dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100

    - name: ğŸ”— Restore dependencies
      run: dotnet restore

    - name: ğŸ“‚ Create new nuget package
      run: dotnet pack --configuration Release

    - name: ğŸš€ Push new nuget package
      run: dotnet nuget push ./bin/Release/REGON.${{ github.ref_name }}.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}